---
version: "2"
linters:
  settings:
    gocognit:
      min-complexity: 20
    goconst:
      numbers: true
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        # TODO: enable it once hits the cloud. I test it with http, so
        # skipping it for now
        - G124
        # I rely on random only in tests, and crypto/rand has ugly api
        - G404
    nakedret:
      max-func-lines: 0
    nestif:
      min-complexity: 3
    paralleltest:
      check-cleanup: true
    testifylint:
      go-require:
        ignore-http-handlers: true
  enable:
    - bidichk
    - copyloopvar
    - decorder
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errname
    - errorlint
    - funcorder
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - gosmopolitan
    - govet
    - iface
    - interfacebloat
    - intrange
    - iotamixing
    - misspell
    - mnd
    - modernize
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - testpackage
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
