---
name: acceptance tests
on: pull_request

concurrency:
  group: acceptance-${{ github.event.repository.name }}

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: sudo apt list --installed
      - run: sudo apt purge google-chrome-stable
      - run: sudo apt purge chromium-browser
      - run: sudo apt update -y
      - run: sudo apt install build-essential xvfb -y
      - run: make spec

  approve-pull-request:
    if: |
      always()
      && !contains(needs.*.result, 'failure')
      && !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    needs:
      - acceptance
    steps:
      - uses: actions/checkout@v4
      - run: gh pr review "${{ github.event.number }}" --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
