---
name: commit checks

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!main"

concurrency:
  group: commit-checks-${{ github.event.repository.name }}-${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/toolset
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/toolset
      - run: make test
